from databricks import sql
from typing import Dict, Any, List
import config
from datetime import datetime


class DatabricksHandler:
    def __init__(self):
        self.connection = None
        self.connect()
    
    def connect(self):
        """Establish connection to Databricks"""
        try:
            self.connection = sql.connect(
                server_hostname=config.DATABRICKS_HOST,
                http_path=config.DATABRICKS_HTTP_PATH,
                personal_access_token=config.DATABRICKS_TOKEN
            )
            print("Connected to Databricks successfully")
        except Exception as e:
            print(f"Error connecting to Databricks: {e}")
            raise
    
    def create_table_if_not_exists(self):
        """Create the job applications table if it doesn't exist"""
        try:
            with self.connection.cursor() as cursor:
                create_table_query = f"""
                CREATE TABLE IF NOT EXISTS {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.{config.DATABRICKS_TABLE} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    message_id STRING NOT NULL UNIQUE,
                    from_email STRING,
                    to_email STRING,
                    subject STRING,
                    email_date STRING,
                    received_timestamp TIMESTAMP,
                    company STRING,
                    job_title STRING,
                    application_status STRING,
                    application_url STRING,
                    email_body STRING,
                    keywords_found STRING,
                    processed_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
                cursor.execute(create_table_query)
                print(f"Table {config.DATABRICKS_TABLE} ready")
        except Exception as e:
            print(f"Error creating table: {e}")
    def create_tables_if_not_exist(self):
        """Create both OLTP (transactional) and OLAP (analytics) table schemas"""
        try:
            with self.connection.cursor() as cursor:
                # ===== TRANSACTIONAL SCHEMA (Star Schema - OLTP) =====

                # Dimension: Company
                cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_company (
                    company_dim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_name STRING NOT NULL UNIQUE,
                    domain STRING,
                    first_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """)

                # Dimension: Job Title
                cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_job_title (
                    job_title_dim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title STRING NOT NULL UNIQUE,
                    category STRING,
                    first_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """)

                # Dimension: Date (simple date dimension)
                cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_date (
                    date_dim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    the_date DATE NOT NULL UNIQUE,
                    year INT,
                    month INT,
                    day INT,
                    iso_week INT
                )
                """)

                # Dimension: Email Sender
                cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_sender (
                    sender_dim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sender_email STRING NOT NULL UNIQUE,
                    sender_name STRING
                )
                """)

                # Fact table: Applications
                cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.fact_applications (
                    application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    message_id STRING NOT NULL UNIQUE,
                    company_dim_id BIGINT,
                    job_title_dim_id BIGINT,
                    sender_dim_id BIGINT,
                    date_dim_id BIGINT,
                    to_email STRING,
                    subject STRING,
                    application_status STRING,
                    application_url STRING,
                    received_timestamp TIMESTAMP,
                    email_body STRING,
                    keywords STRING,
                    processed_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """)
                
                # ===== ANALYTICS SCHEMA (Denormalized - OLAP) =====
                
                # Denormalized analytics view
                cursor.execute(f"""
                CREATE TABLE IF NOT EXISTS {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.applications_analytics (
                    application_id BIGINT,
                    message_id STRING,
                    company_name STRING,
                    company_id BIGINT,
                    job_title STRING,
                    job_title_id BIGINT,
                    from_email STRING,
                    to_email STRING,
                    subject STRING,
                    email_date STRING,
                    application_status STRING,
                    application_url STRING,
                    received_timestamp TIMESTAMP,
                    keywords_found STRING,
                    email_body_length INT,
                    processed_timestamp TIMESTAMP,
                    synced_to_analytics TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """)
                
                print("✓ Transactional (OLTP) schema created")
                print("✓ Analytics (OLAP) schema created")
        
        except Exception as e:
            print(f"Error creating tables: {e}")
    
    def get_or_create_company(self, company_name: str) -> int:
        """Get company_dim_id or create new company dimension"""
        try:
            with self.connection.cursor() as cursor:
                cursor.execute(f"""
                SELECT company_dim_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_company
                WHERE company_name = ?
                """, (company_name,))
                result = cursor.fetchone()
                if result:
                    return result[0]
                cursor.execute(f"""
                INSERT INTO {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_company (company_name)
                VALUES (?)
                """, (company_name,))
                cursor.execute(f"""
                SELECT company_dim_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_company
                WHERE company_name = ?
                """, (company_name,))
                return cursor.fetchone()[0]
        except Exception as e:
            print(f"Error with company lookup: {e}")
            return None
    
    def get_or_create_job_title(self, job_title: str) -> int:
        """Get job_title_dim_id or create new job title dimension"""
        try:
            with self.connection.cursor() as cursor:
                cursor.execute(f"""
                SELECT job_title_dim_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_job_title
                WHERE title = ?
                """, (job_title,))
                result = cursor.fetchone()
                if result:
                    return result[0]
                cursor.execute(f"""
                INSERT INTO {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_job_title (title)
                VALUES (?)
                """, (job_title,))
                cursor.execute(f"""
                SELECT job_title_dim_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_job_title
                WHERE title = ?
                """, (job_title,))
                return cursor.fetchone()[0]
        except Exception as e:
            print(f"Error with job title lookup: {e}")
            return None

    def get_or_create_date(self, date_str: str) -> int:
        """Get date_dim_id or create new date dimension. Expects ISO date string or empty."""
        try:
            if not date_str:
                return None
            the_date = None
            try:
                the_date = datetime.fromisoformat(date_str).date()
            except Exception:
                try:
                    the_date = datetime.fromisoformat(date_str.split('T')[0]).date()
                except Exception:
                    return None
            year = the_date.year
            month = the_date.month
            day = the_date.day
            iso_week = the_date.isocalendar()[1]
            with self.connection.cursor() as cursor:
                cursor.execute(f"""
                SELECT date_dim_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_date
                WHERE the_date = ?
                """, (the_date,))
                result = cursor.fetchone()
                if result:
                    return result[0]
                cursor.execute(f"""
                INSERT INTO {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_date (the_date, year, month, day, iso_week)
                VALUES (?, ?, ?, ?, ?)
                """, (the_date, year, month, day, iso_week))
                cursor.execute(f"""
                SELECT date_dim_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_date
                WHERE the_date = ?
                """, (the_date,))
                return cursor.fetchone()[0]
        except Exception as e:
            print(f"Error with date lookup: {e}")
            return None

    def get_or_create_sender(self, sender_email: str, sender_name: str = None) -> int:
        """Get sender_dim_id or create new sender dimension"""
        try:
            with self.connection.cursor() as cursor:
                cursor.execute(f"""
                SELECT sender_dim_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_sender
                WHERE sender_email = ?
                """, (sender_email,))
                result = cursor.fetchone()
                if result:
                    return result[0]
                cursor.execute(f"""
                INSERT INTO {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_sender (sender_email, sender_name)
                VALUES (?, ?)
                """, (sender_email, sender_name))
                cursor.execute(f"""
                SELECT sender_dim_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_sender
                WHERE sender_email = ?
                """, (sender_email,))
                return cursor.fetchone()[0]
        except Exception as e:
            print(f"Error with sender lookup: {e}")
            return None
    
    def store_application(self, email_data: Dict[str, Any]) -> bool:
        """Store job application data in Databricks"""
        try:
            with self.connection.cursor() as cursor:
                extracted = email_data.get('extracted_info', {})
                keywords_list = extracted.get('keywords_found', [])
                company_name = extracted.get('company', 'Unknown')
                job_title = extracted.get('job_title', 'Not specified')
                sender = email_data.get('from', '')

                # Resolve dimensions
                company_dim_id = self.get_or_create_company(company_name)
                job_title_dim_id = self.get_or_create_job_title(job_title)
                date_dim_id = self.get_or_create_date(email_data.get('date', ''))
                sender_dim_id = self.get_or_create_sender(sender)

                # Insert into fact_applications
                cursor.execute(f"""
                INSERT INTO {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.fact_applications
                (message_id, company_dim_id, job_title_dim_id, sender_dim_id, date_dim_id,
                 to_email, subject, application_status, application_url, received_timestamp,
                 email_body, keywords)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    email_data['message_id'],
                    company_dim_id,
                    job_title_dim_id,
                    sender_dim_id,
                    date_dim_id,
                    email_data.get('to', ''),
                    email_data.get('subject', ''),
                    extracted.get('application_status', ''),
                    extracted.get('application_url', ''),
                    email_data.get('timestamp', None),
                    email_data.get('body', '')[:5000],
                    ','.join(keywords_list)
                ))

                # Get the application_id
                cursor.execute(f"""
                SELECT application_id FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.fact_applications
                WHERE message_id = ?
                """, (email_data['message_id'],))
                app_id = cursor.fetchone()[0]

                # Sync to analytics table (flattened)
                self._sync_to_analytics(app_id)
                print(f"Stored application (fact) id={app_id} company={company_name}")
                return True
        except Exception as e:
            if 'UNIQUE constraint failed' in str(e) or 'unique' in str(e).lower():
                print(f"Message already stored: {email_data.get('message_id')}")
                return False
            print(f"Error storing application: {e}")
            return False
    
    def _sync_to_analytics(self, application_id: int):
        """Sync a single application to the analytics denormalized table"""
        try:
            with self.connection.cursor() as cursor:
                # Get the fact row and join to dimensions
                cursor.execute(f"""
                SELECT 
                    fa.application_id,
                    fa.message_id,
                    dc.company_name,
                    fa.company_dim_id,
                    dj.title,
                    fa.job_title_dim_id,
                    ds.sender_email,
                    fa.to_email,
                    fa.subject,
                    dd.the_date,
                    fa.application_status,
                    fa.application_url,
                    fa.received_timestamp,
                    fa.email_body,
                    fa.keywords,
                    fa.processed_timestamp
                FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.fact_applications fa
                LEFT JOIN {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_company dc
                    ON fa.company_dim_id = dc.company_dim_id
                LEFT JOIN {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_job_title dj
                    ON fa.job_title_dim_id = dj.job_title_dim_id
                LEFT JOIN {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_sender ds
                    ON fa.sender_dim_id = ds.sender_dim_id
                LEFT JOIN {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.dim_date dd
                    ON fa.date_dim_id = dd.date_dim_id
                WHERE fa.application_id = ?
                """, (application_id,))

                result = cursor.fetchone()
                if not result:
                    return

                # Insert into analytics table (flattened)
                cursor.execute(f"""
                INSERT INTO {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.applications_analytics
                (application_id, message_id, company_name, company_id, job_title, job_title_id,
                 from_email, to_email, subject, email_date, application_status, application_url,
                 received_timestamp, keywords_found, email_body_length, processed_timestamp)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    result[0], result[1], result[2], result[3], result[4], result[5],
                    result[6], result[7], result[8], str(result[9]) if result[9] else None,
                    result[10], result[11], result[12], result[14] if result[14] else '',
                    len(result[13]) if result[13] else 0, result[15]
                ))
        
        except Exception as e:
            print(f"Error syncing to analytics: {e}")
    
    def get_all_applications(self, limit: int = 100) -> List[Dict[str, Any]]:
        """Retrieve all applications from analytics table (denormalized)"""
        try:
            with self.connection.cursor() as cursor:
                query = f"""
                SELECT * FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.applications_analytics
                ORDER BY processed_timestamp DESC
                LIMIT {limit}
                """
                cursor.execute(query)
                columns = [description[0] for description in cursor.description]
                results = []
                for row in cursor.fetchall():
                    results.append(dict(zip(columns, row)))
                return results
        
        except Exception as e:
            print(f"Error retrieving applications: {e}")
            return []
    
    def get_applications_by_status(self, status: str, limit: int = 50) -> List[Dict[str, Any]]:
        """Retrieve applications filtered by status from analytics table"""
        try:
            with self.connection.cursor() as cursor:
                query = f"""
                SELECT * FROM {config.DATABRICKS_CATALOG}.{config.DATABRICKS_SCHEMA}.applications_analytics
                WHERE application_status = ?
                ORDER BY processed_timestamp DESC
                LIMIT {limit}
                """
                cursor.execute(query, (status,))
                columns = [description[0] for description in cursor.description]
                results = []
                for row in cursor.fetchall():
                    results.append(dict(zip(columns, row)))
                return results
        
        except Exception as e:
            print(f"Error retrieving applications by status: {e}")
            return []
    
    def close(self):
        """Close Databricks connection"""
        if self.connection:
            self.connection.close()
